### ISSUE TITLE
How can we use this ts-migrate？

### ISSUE THREAD

**Issue by wellmoon0** [airbnb/ts-migrate#11]
Hello everyone, how can we use this ts-migrate? Could you please provide us a demo about how a javascript file to typescript file when use this ts-migrate

**Comment by kazekage605** [comment]
here is the guide.
https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate

**Comment by Rudeg** [comment]
You should follow instructions from the [readme](https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate/README.md) in the ts-migrate package.
You can also check [the blog post](https://medium.com/airbnb-engineering/ts-migrate-a-tool-for-migrating-to-typescript-at-scale-cd23bfeb5cc), which explains some details around ts-migrate.
In addition to that, you can check [plugin tests](https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate-plugins/tests/src), to see what transformations they do.
