### ISSUE TITLE
explicit-any plugin fails to parse arrow function with implicit return of a literal object 

### ISSUE THREAD

**Issue by rdsedmundo** [airbnb/ts-migrate#113]
Command: `yarn ts-migrate-full ./test-project --plugin explicit-any`

Input:
```js
export const fn = ({ arg }) => {
  return {
    a: arg.map((b) => ({
      c: b.property,
    })),
  };
};
```

Output:
```ts
export const fn = ({
  arg
}: any) => {
  return {
    a: arg.map((b: any) => {
      c: b.property,
    }),
  };
};
```

The surrounding parenthesis are being removed.

**Comment by rdsedmundo** [comment]
Downgrading to `0.1.16` makes it work again. I had to force the resolution on Yarn by the way, because the main package releases the dependent packages with a caret (`ˆ`) in the version, so it always picks up the latest—might be something worth changing).

**Comment by rdsedmundo** [comment]
@edsrzf From my investigation I think this is related to the latest dependencies update you did, somehow it broke the logic we have for diagnostic.code=1006.

**Comment by edsrzf** [comment]
Yep, will do. Thanks for all the detail.

**Comment by edsrzf** [comment]
It looks like this was introduced when we upgraded jscodeshift in #106. Trying to figure out the appropriate fix...

**Comment by edsrzf** [comment]
Upstream issue is here: https://github.com/benjamn/recast/issues/743 (recast is a jscodeshift dependency)

Two PRs claiming to fix it, unreviewed and unmerged:
* https://github.com/benjamn/recast/pull/744
* https://github.com/benjamn/recast/pull/830
