### ISSUE TITLE
Lerna migration

### ISSUE THREAD

**Issue by tiziodcaio** [airbnb/ts-migrate#129]
I suggest everyone to update to yarn v2. Otherwise at the moment lerna doesn't support it, so the migration cannot be done. What should you want to do? I found this about the problem: lerna/lerna/issues/2449

**Comment by Rudeg** [comment]
@tiziodcaio For now, `lerna` covers everything what we need, so there is not that much benefit in the migration.
Feel free to open a PR, if you want to contribute and benefit from doing it!
