### ISSUE TITLE
how to use plugins?

### ISSUE THREAD

**Issue by danielo515** [airbnb/ts-migrate#136]
Hello.
Thanks for this fantastic tool, really looks like it's going to reduce my dev time.
On my current project I have JSDoc annotations for almost all the files. How can I make ts-migrate take those into account? It will really speed up my work.

Thanks in advance

**Comment by jasonk** [comment]
For anybody that ends up here from Google like I did:

The issue that mentions this one (about Documenting the `--plugin` option) is not the answer. The answer is "you cannot" as the plugins that get loaded are hard-coded in the CLI tool.  The `--plugin` option lets you only run a single plugin, but it still has to be one of the default ones, you can't load your own plugins with the `ts-migrate` CLI.

In the end what I had to do was to take the example code from `packages/ts-migrate-example/src/index.ts` and combine it with the default plugin loading from `packages/ts-migrate/cli.ts` to create my own CLI tool with the plugins I wanted to run.

**Comment by danielo515** [comment]
> For anybody that ends up here from Google like I did:
> 
> The issue that mentions this one (about Documenting the `--plugin` option) is not the answer. The answer is "you cannot" as the plugins that get loaded are hard-coded in the CLI tool. The `--plugin` option lets you only run a single plugin, but it still has to be one of the default ones, you can't load your own plugins with the `ts-migrate` CLI.
> 
> In the end what I had to do was to take the example code from `packages/ts-migrate-example/src/index.ts` and combine it with the default plugin loading from `packages/ts-migrate/cli.ts` to create my own CLI tool with the plugins I wanted to run.

This was the actual answer I was looking for. Thanks
