### ISSUE TITLE
 Cannot read property 'createTypeReferenceNode' of undefined

### ISSUE THREAD

**Issue by xzzdll** [airbnb/ts-migrate#138]
when I run npx ts-migrate-full <fold>, l get this error.  
Can somebody help me resolve this?  Thanks

 typeRef: typescript_1.default.factory.createTypeReferenceNode('WithStylesProps', undefined),
TypeError: Cannot read property 'createTypeReferenceNode' of undefined

**Comment by kaleem-elahi** [comment]
Getting same issue

`TypeError: Cannot read property 'createTypeReferenceNode' of undefined`

**Comment by gs-ivalath** [comment]
> Getting same issue
> 
> `TypeError: Cannot read property 'createTypeReferenceNode' of undefined`

Upgrade typescript to 4.0+ and you should be good
