### ISSUE TITLE
Use runtime information to resolve "any" types

### ISSUE THREAD

**Issue by mikeslattery** [airbnb/ts-migrate#156]
I don't expect this to be done as it would be a huge amount of work, but it would be VERY cool.

The idea is to instrument code (much like code coverage tools do) to record the data type of method parameters and return values during runtime.  The output information dump could be fed into `ts-migrate` so that it knows what types were used.  This could eliminate most uses of `any` in the final output.

It would be best if you could aggregate instrumentation data from several runs, so you could combine output from unit tests, E2E tests, node REPL usage, and normal manual use of the app.

If multiple types were used for a parameter or return type over multiple calls, then it could resolve to a 1) common parent type (too hard?) perhaps with a type assertion per call, 2) union type, 3) intersection type, or 4) `any`.  Of course, if a method was never called, you'd have to fallback to `any`.

It could add the optional indicator (`?:`) for `undefined` or `null` values.

**Comment by devinrhode2** [comment]
Checkout typewiz, does exactly that. Was very recently "archived". Also typestat is really interesting.

**Comment by mikeslattery** [comment]
@devinrhode2 I don't see that typewiz does this.  Typestat is interesting, but does static analysis like ts-migrate; it doesn't do dynamic runtime analysis.

**Comment by mikeslattery** [comment]
I closed this because [typewiz](https://github.com/urish/typewiz) does exactly what I wanted, although it's no longer maintained and I haven't tested it yet.  Thanks @devinrhode2
