### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by JamesSingleton** [airbnb/ts-migrate#16]
Given a folder structure like
```
my-app
├── README.md
├── node_modules
├── package.json
├── .gitignore
├── public
│   ├── favicon.ico
│   ├── index.html
│   └── manifest.json
└── src
    ├── App.css
    ├── App.js
    ├── App.test.js
    ├── index.css
    ├── index.js
    ├── logo.svg
    └── serviceWorker.js
    └── setupTests.js
```
When I `cd` into `my-app`, `npm i -D ts-migrate` and run `npx ts-migrate-full src` I am told that the system cannot find the path specified.

## System:
 - OS: Windows 10 10.0.19042
 - CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
 - Memory: 7.43 GB / 15.95 GB
## Binaries:
 - Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.8 - D:\Coding\github_work\fetchye\node_modules\.bin\npm.CMD
## npmGlobalPackages:
 - npm: 6.14.6

**Comment by JamesSingleton** [comment]
So it looks like I had to `npm i -g ts-migrate`. Furthermore, it looks like it doesn't work in PowerShell and had to switch over to Git Bash. However, now when I do `ts-migrate-full src`, I get
```
Welcome to TS Migrate! :D

This script will migrate a frontend folder to a compiling (or almost compiling) TS project.

It is recommended that you take the following steps before continuing...

1. Make sure you have a clean git slate.
   Run `git status` to make sure you have no local changes that may get lost.
   Check in or stash your changes, then re-run this script.

2. Check out a new branch for the migration.
   For example, `git checkout -b james--ts-migrate` if you're migrating several folders or
   `git checkout -b james--ts-migrate-.` if you're just migrating ..

3. Make sure you're on the latest, clean master.
   `git fetch origin master && git reset --hard origin/master`

4. Make sure you have the latest npm modules installed.
   `npm install` or `yarn install`

If you need help or have feedback, please file an issue on Github!

Continue? (y/N) Y
```
However, it looks like only `ts-migrate-full` and `reignore` are installed globally, `ts-migrate` is not. Due to this, it fails because it cannot find `npm/node_modules/ts-migrate/bin/ts-migrate`

**Comment by alydemah** [comment]
I'm having the same issue as well,
following @JamesSingleton tip then try to run from git Bash
I get this error

```
Welcome to TS Migrate! :D

This script will migrate a frontend folder to a compiling (or almost compiling) TS project.

It is recommended that you take the following steps before continuing...

1. Make sure you have a clean git slate.
   Run `git status` to make sure you have no local changes that may get lost.
   Check in or stash your changes, then re-run this script.

2. Check out a new branch for the migration.
   For example, `git checkout -b aly--ts-migrate` if you're migrating several folders or
   `git checkout -b aly--ts-migrate-new` if you're just migrating new.

3. Make sure you're on the latest, clean master.
   `git fetch origin master && git reset --hard origin/master`

4. Make sure you have the latest npm modules installed.
   `npm install` or `yarn install`

If you need help or have feedback, please file an issue on Github!

Continue? (y/N) y
Set a custom path for the typescript compiler. (It's an optional step. Skip if you don't need it. Default path is ./node_modules/.bin/tsc.):
Your default tsc path is ./node_modules/.bin/tsc.

[Step 1 of 4] Initializing ts-config for the "new"...

C:\Users\aly\AppData\Roaming\npm/node_modules/ts-migrate/bin/ts-migrate-full.sh: line 66: C:\Users\aly\AppData\Roaming\npm/node_modules/ts-migrate/bin/ts-migrate: No such file or directory
```

**Comment by JamesSingleton** [comment]
> I'm having the same issue as well,
> following @JamesSingleton tip then try to run from git Bash
> I get this error
> 
> ```
> Welcome to TS Migrate! :D
> 
> This script will migrate a frontend folder to a compiling (or almost compiling) TS project.
> 
> It is recommended that you take the following steps before continuing...
> 
> 1. Make sure you have a clean git slate.
>    Run `git status` to make sure you have no local changes that may get lost.
>    Check in or stash your changes, then re-run this script.
> 
> 2. Check out a new branch for the migration.
>    For example, `git checkout -b aly--ts-migrate` if you're migrating several folders or
>    `git checkout -b aly--ts-migrate-new` if you're just migrating new.
> 
> 3. Make sure you're on the latest, clean master.
>    `git fetch origin master && git reset --hard origin/master`
> 
> 4. Make sure you have the latest npm modules installed.
>    `npm install` or `yarn install`
> 
> If you need help or have feedback, please file an issue on Github!
> 
> Continue? (y/N) y
> Set a custom path for the typescript compiler. (It's an optional step. Skip if you don't need it. Default path is ./node_modules/.bin/tsc.):
> Your default tsc path is ./node_modules/.bin/tsc.
> 
> [Step 1 of 4] Initializing ts-config for the "new"...
> 
> C:\Users\aly\AppData\Roaming\npm/node_modules/ts-migrate/bin/ts-migrate-full.sh: line 66: C:\Users\aly\AppData\Roaming\npm/node_modules/ts-migrate/bin/ts-migrate: No such file or directory
> ```
> 
> 
> 

Yup! I get the same error as well.

**Comment by JamesSingleton** [comment]
So it looks like it doesn't like windows paths... It works on macOS though

**Comment by lencioni** [comment]
We'd love to review a PR that improves support for Windows if you are interested in submitting one!

**Comment by JamesSingleton** [comment]
> We'd love to review a PR that improves support for Windows if you are interested in submitting one!

Cool, might try to tackle that this weekend, no promises though.
