### ISSUE TITLE
Typescript 4.4+ prop-type to types not converting

### ISSUE THREAD

**Issue by pd8** [airbnb/ts-migrate#165]
As an FYI, these issue only appears to occur in version 4.4+, I've tested and the codemod works on 4.2, so there is a work around.

For context, at this point I've already run the ... command, which changed the files to be typescript correctly

```
npx ts-migrate rename . \
    --sources "./ConfirmationModal/index.jsx"
```

When following up with ...

```
npx ts-migrate migrate . \
    --sources "./ConfirmationModal/index.tsx" \
    --sources "node_modules/**/*.d.ts" \
    --aliases tsfixme
```
The command would not be able to generate types from a "simple" react component that had prop types.
On further testing this was because of the typescript version (4.6), debugging the react-props plugin, I found this interesting behaviour

Here ..., we're trying to find if there is an import declaration for prop-types, funnily the `isImportDeclaration` doesn't return true in v4.4+ - I believe this is the cause of the bug.

https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/react-props.ts#L54

The codemod doesn't outright error and it adds most types correctly, but without prop-types being changed to types in results in significantly more type errors than required.

Test file ConfirmationModal.tsx
```
import React from "react";
import pt from "prop-types";

const Modal = () => <div>Fake Modal</div>;
const CONFIRMATION_MODAL_SUCCESS = "CONFIRMATION_MODAL_SUCCESS";
const CONFIRMATION_MODAL_ERROR = "CONFIRMATION_MODAL_ERROR";

const ConfirmationModal = (props) => {
  const {
    loading,
    result,
    title,
    successTitle,
    errorTitle,
    bodyDescription,
    bodyItems,
    bodyOnConfirmDescription,
    successBody,
    errorBody,
    cancelText,
    confirmText,
    onConfirm,
    onCancel,
    secondaryText,
    secondaryAction,
  } = props;

  let modalTitle;
  let modalBody;

  switch (result) {
    case CONFIRMATION_MODAL_SUCCESS:
      modalTitle = successTitle || title;
      modalBody = <div>{successBody}</div>;
      break;
    case CONFIRMATION_MODAL_ERROR:
      modalTitle = errorTitle || title;
      modalBody = <div>{errorBody}</div>;
      break;
    default:
      modalTitle = title;
      modalBody = (
        <div>
          <p>{bodyDescription}</p>
          {bodyItems.map((item, index) => (
            <p key={index}>
              <p inline bold>
                {item.boldText}
              </p>{" "}
              {item.text}
            </p>
          ))}
          <p>{bodyOnConfirmDescription}</p>
        </div>
      );
  }
  return (
    <Modal
      isOpen
      isLoading={loading}
      modalTitle={modalTitle}
      cancelText={cancelText || "Cancel"}
      secondaryText={secondaryText}
      submitText={confirmText || "Confirm"}
      onSubmit={onConfirm}
      onCancel={onCancel}
      onSecondaryAction={secondaryAction}
      isSubmitable={result !== CONFIRMATION_MODAL_ERROR}
      hasSecondaryAction={
        !!secondaryAction && result === CONFIRMATION_MODAL_SUCCESS
      }
    >
      {modalBody}
    </Modal>
  );
};

ConfirmationModal.propTypes = {
  title: pt.string.isRequired,
  successTitle: pt.string,
  errorTitle: pt.string,
  bodyDescription: pt.string,
  bodyItems: pt.arrayOf(
    pt.shape({ boldText: pt.string, text: pt.string.isRequired })
  ),
  bodyOnConfirmDescription: pt.string,
  successBody: pt.string.isRequired,
  errorBody: pt.string.isRequired,
  cancelText: pt.string,
  confirmText: pt.string,
  onCancel: pt.func,
  onConfirm: pt.func,
  secondaryAction: pt.func,
  secondaryText: pt.string,
};

export default ConfirmationModal;
```

**Comment by xunjiang** [comment]
There is more than that, the namedBindings is also missing

**Comment by skovy** [comment]
It seems like this may be due to using https://www.npmjs.com/package/@ts-morph/bootstrap and the `typescript` package?

https://github.com/dsherret/ts-morph/blob/40e9bf6563879e866601f3f68a18b9c1e63b3fb5/packages/ts-morph/breaking-changes.md#version-10 claims TypeScript is bundled and the error seen here seems to be a mismatch between enum values for `kind` on nodes

**Comment by Rudeg** [comment]
could you please try the latest version?

**Comment by dlemburg** [comment]
This seems to be an issue still. Similar to the above comments, I cannot get the 'react-props' plugin to create types. The [LOC](https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/react-props.ts#L54) referenced above seems problematic in that when stepping through, the kind on the 'prop-types' `node.kind` is not matching `isImportDeclaration` (fwiw 266 vs 262). I've tried downgrading multiple version of both typescript and ts-migrate. 

Any thoughts / anything more context / anything else I can do to help look into this?

**Comment by dlemburg** [comment]
Can confirm that latest version of typescript and ts-migrate fixes this issue.
