### ISSUE TITLE
Prop-types and defaultprops not converting with latest version plus jsx comments are also not used

### ISSUE THREAD

**Issue by attentive-nimesh** [airbnb/ts-migrate#194]
The prop-types are not converting into type as well as in jsx component it giving //@ts-expect error ... which is throwing error as in jsx {/* @ts-expect error,,,*/} should pass

**Comment by jporzelt** [comment]
Is was able to fix the migration by aligning the library versions (especially typescript -> 4.7.2) with the ones defined in ts-migrate
