### ISSUE TITLE
[Feature] Output Types from JSDoc comments

### ISSUE THREAD

**Issue by monsonjeremy** [airbnb/ts-migrate#20]
I think it would be really awesome to be able to use types that are defined in JSDoc comments to output types with this tool. Seems that it would be developed as a plugin for the base tool. 

I'd be happy to try and start this work, but have to admit I have pretty cursory knowledge of Typescript and would not really know where to start.

**Comment by Rudeg** [comment]
@monsonjeremy Yes, that could be a very cool plugin!

You can start by looking into the typescript compiler API for [getting jsdoc information for a specific node](https://github.com/microsoft/TypeScript/blob/59ad375234dc2efe38d8ee0ba58414474c1d5169/src/compiler/utilitiesPublic.ts#L862).
As a starting point for the plugin, you could use an [example ts compiler plugin](https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-example/src/example-plugin-ts.ts).

Feel free to ask any questions - I'll try to help :)

**Comment by edsrzf** [comment]
I'm having a look at doing this adapting code from the [existing code fix to annotate types using JSDoc](https://github.com/microsoft/TypeScript/blob/v4.0.2/src/services/codefixes/annotateWithTypeFromJSDoc.ts). It looks like it should be possible to get something working but doesn't feel great to be copying all this code.

I'm not familiar enough with any of this to say whether there might be another, better option.

**Comment by monsonjeremy** [comment]
@edsrzf Awesome stuff! Thanks for doing this 💯
