### ISSUE TITLE
Unable to migrate js file to ts

### ISSUE THREAD

**Issue by golu7679** [airbnb/ts-migrate#201]
After the installation of ts-migrate package, when I run **npx -p ts-migrate -c "ts-migrate-full ."**

I receive an error **"An error occurred mounting one of your file systems. Please run 'dmesg' for more details."**

How can I resolve this issue?

**Comment by elimelt** [comment]
What platform/OS are you experiencing this problem on (I'm assuming WSL)? It seems indicative of an underlying issue with your WSL filesystem configuration, although I'd need more info to further assist you. 

Did you try running `dmesg`? Copy and paste the output here.

**Comment by Prakhargarg-2010196** [comment]
> After the installation of ts-migrate package, when I run **npx -p ts-migrate -c "ts-migrate-full ."**
> 
> I receive an error **"An error occurred mounting one of your file systems. Please run 'dmesg' for more details."**
> 
> How can I resolve this issue?
First @golu7679  tell me if this is a test repo or a larger codebase cause things can break?

**Comment by Prakhargarg-2010196** [comment]
If it is a test repo or one you can experiment with then run the following commands if they do the trick for you!!
First remove all the ts-migrate globally or locally already present!!
Can you try these commands from the repo and tell me if the issue is resolved? 
```sh
// Installs the ts-migrate as the local dev dependency    
npm install --save-dev ts-migrate 
// Initialize the tsconfig.json file in the repository   
   npm exec ts-migrate -- init .   
// Execute the ts-migrate-full.sh available from the ts-migrate package
   npm exec --package ts-migrate -c "ts-migrate-full ." 

```
