### ISSUE TITLE
Proptypes plugin fails when proptypes are destructured

### ISSUE THREAD

**Issue by arthuralee** [airbnb/ts-migrate#24]
The prop types plugin fails to properly convert proptypes to TS types when the proptypes import is destructured. See the below example:

```
import React from "react";
import { node, string } from "prop-types";

const Foo = ({ children, className }) => {
  return <div className={className}>children</div>;
};

Foo.propTypes = {
  children: node,
  className: string,
};

export default Foo;
```

Relevant code:
https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/utils/react-props.ts#L115

The check on this line fails and a type reference node is created instead. Not sure what the best solution would be but it would probably involve keeping track of the identifiers from the import of `prop-types`. Happy to hear any pointers and I could take a stab at writing a PR for it.

**Comment by Rudeg** [comment]
@arthuralee yes, you're right. The solution to this would be to use https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/utils/react-props.ts#L15 on the propTypes value itself and it should generate a correct type from this.

**Comment by arthuralee** [comment]
Could you clarify a bit on what you meant? It seems like `getTypeFromPropTypesObjectLiteral()` wouldn't help since `getTypeFromPropTypeExpression()` doesn't know when an identifier is actually a destructured PropType object if its not a property access expression.

I came up with a solution that seemed kind of involved, but I wonder if it's the right way forward. It involves parsing through the proptypes import, keeping track of the import specifiers in a map and then later. Initial draft here #36

**Comment by Rudeg** [comment]
@arthuralee sorry for the delay :( 
Yes, you're right, I miss-understand your initial question =/
I think your approach is a good way to move forward.
