### ISSUE TITLE
Flag to preserve PropTypes

### ISSUE THREAD

**Issue by coderaiser** [airbnb/ts-migrate#33]
Would be amazing if `ts-migrate` support `flag` to preserve `PropTypes`. Right now this part 
should be commented for this purpose:
https://github.com/airbnb/ts-migrate/blob/1169c21fe694f7b885636075b94b6db9ec366860/packages/ts-migrate-plugins/src/plugins/react-props.ts#L31-L35

**Comment by Rudeg** [comment]
Fixed by https://github.com/airbnb/ts-migrate/pull/86
