### ISSUE TITLE
Plugin to add class accessibility modifiers

### ISSUE THREAD

**Issue by edsrzf** [airbnb/ts-migrate#42]
Our JavaScript code base has a convention of prefixing private class properties and methods with underscores (eg `_privateProperty`). It would be great to have a ts-migrate plugin that would apply the appropriate accessibility modifier (`private`, `protected`, or `public`) based on this convention or similar ones.

As a sketch of a design, it could be regex-based and have these options:

```ts
type Options = {
  // The default accessibility modifier to add if there is no regex match.
  // undefined means that there is no modifier applied when no regex matches,
  // and the class element defaults to public.
  defaultModifier?: 'private' | 'protected' | 'public'

  // If a class element matches this regex, it is marked as private.
  privateRegex?: string;

  // If a class element matches this regex, it is marked as protected.
  protectedRegex?: string;

  // If a class element matches this regex, it is marked as public.
  publicRegex?: string;
};
```

If multiple regexes match, the priority is `private` > `protected` > `public`. The default options mean that no transformations are made.

The options I would use for the code base I'm working with would be:

```json
{
  "defaultModifier": "public",
  "privateRegex": "^_"
}
```

This means that any class elements whose names match the regex `/^_/` would be marked `private` and all other elements would be marked `public`. (We do not have a convention for `protected` names, and have very few in practice.)

Is this something that would be useful? Could it even be a default plugin, considering that the default options do nothing? Are there any thoughts on the design above?

**Comment by Rudeg** [comment]
@edsrzf thanks for the idea, I love it!
Sound's like it would be a nice fit for the default plugins. 
Design above looks good to me as well!
