### ISSUE TITLE
how to remove all Unused '@ts-expect-error' directive

### ISSUE THREAD

**Issue by nieyao** [airbnb/ts-migrate#48]
after run npx ts-migrate-full <folder>, I receive many errors about alias. after i resolve it.these annotation 
// @ts-expect-error ts-migrate(2307) FIXME: Cannot find module '@/constants/types' or its corr... Remove this comment to see the full error message
now, i want remove all annotations like it .

**Comment by edsrzf** [comment]
Try `ts-migrate reignore`. This command strips all `@ts-expect-error` comments, then re-applies `@ts-expect-error` anywhere that still has errors.

**Comment by nieyao** [comment]
I try the Usage README.md,but its not work,
I try npx ts-migrate -- reignore, Must provide a command.
I try  npm run ts-migrate -- reignore ./src ,but ts-migrate is a script , i receive a error like npm ERR! missing script: ts-migrate,
but i can't find the script:ts-migrate in README.md

**Comment by Pierre-CLIND** [comment]
You can try:
`> ts-migrate reignore ./src  `

**Comment by nieyao** [comment]
oh,don't need -- before reignore ,please update README.md ,thx

**Comment by nieyao** [comment]
> You can try:
> `> ts-migrate reignore ./src `

>`> npx ts-migrate reignore ./  ` work ,thank you

**Comment by emosheeep** [comment]
Sometimes the unused `@ts-expect-error` directives can not be stripped anyway. So I made a simple tool to remove these lines by reading and parsing ts compile log, more here [emosheeep/commover](https://github.com/emosheeep/commover).

Compile ts, output a log file, and then call `commover` command with the file.

```shell
tsc --noEmit > tsc.log # or tsc -b, output compile log to `tsc.log`
commover tsc.log # will read `tsc.log` and handle parsed errors as need
```
Then you'll get these logs

```
Removed line: src/tests/demo.ts:3
Removed line: src/index.ts:3
...
```
