### ISSUE TITLE
Type 'C' cannot be used to index type 'Commands'.

### ISSUE THREAD

**Issue by irenevp** [airbnb/ts-migrate#51]
I am getting this compiler error.
```
node_modules/ts-migrate-server/build/src/tsserver/commands.d.ts:303:66 - error TS2536: Type 'C' cannot be used to index type 'Commands'.

303 export declare type CommandRequest<C extends tsp.CommandTypes> = Commands[C]['request'];
```

**Comment by Rudeg** [comment]
@irenevp could you please provide more information about how are you using ts-migrate and env, where are you running it? Thanks!

**Comment by irenevp** [comment]
I've tried to run the ts-migrate-server without clone the repo, in the repo you have a ts-ignore on the corresponding file (commands.d.ts), so I suppose it's a known problem.

**Comment by edsrzf** [comment]
I've also had this problem trying to import `ts-migrate-server` into another project. #49 deletes this file, so if we can get that to a mergeable state, this will no longer be an issue.

**Comment by edsrzf** [comment]
#49 has been merged, so this should no longer be an issue. Give it a try!
