### ISSUE TITLE
How to enable $TSFixMe aliases?

### ISSUE THREAD

**Issue by jackwoz** [airbnb/ts-migrate#55]
What's the easiest way to enable the aliases for `any` etc, since they are disabled by default? Also, is there a way to provide custom aliases?

**Comment by Rudeg** [comment]
You can create a type alias by declaring a new type:

```
type $TSFixMe = any;
```

In terms of custom aliases, unfortunately, you're not able to specify a custom alias.
We need to make some changes [here](https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate/cli.ts#L100) and pass it via `ts-migrate-full`, if we want to expose it there as well.

**Comment by ajaska** [comment]
If you're running the migrate script by itself, you want to pass `--aliases=tsfixme`

**Comment by jasonk** [comment]
With the `--aliases=tsfixme` flag it does use `$TSFixMe` instead of `any`, but it doesn't add any reference to the type alias so every use of it ends up prefixed with `// @ts-expect-error ts-migrate(2304) FIXME: Cannot find name '$TSFixMe'.`

**Comment by ajaska** [comment]
You can toss this in a new or existing .d.ts file in your project:

```typescript
declare global {
  type $TSFixMe = any;
}
```

(there might be a better way, but that’s worked plenty well for us)

**Comment by SK-CSE** [comment]
create a new file named `tsfixme.d.ts` inside  the `src` folder and paste the below
```
type $TSFixMe = any;
type $TSFixMeFunction = (...args: any[]) => any;
```
and run `npx ts-migrate migrate --aliases tsfixme .`
