### ISSUE TITLE
npx ts-migrate-full FOLDER_PATH not working

### ISSUE THREAD

**Issue by TomAndril** [airbnb/ts-migrate#8]
Hello guys,

I've been trying to run the command to execute the scripts but unfortunately the VSCode terminal is not being able to find the specified path, I've tried on many different ways but there is something I'm probably missing out. Can you guys give me some pointers here?

Regards

**Comment by Rudeg** [comment]
It should work fine from VSCode terminal as well. Could you please post an error message or provide more information about an error?

**Comment by CatsMiaow** [comment]
![image](https://user-images.githubusercontent.com/1300172/91007385-c7901900-e616-11ea-8af8-f9d76e26e105.png)
But people will want to run `npx ts-migrate-full` without external dependencies.

**Comment by Rudeg** [comment]
@TomAndril you need to install `ts-migrate` as a dev dependency first - https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate#install and then you should be able to run it

**Comment by AmirTugi** [comment]
It seems weird to install a migration tool as a dependency for 1 time usage.
I'd expect to be able to just do `npx ts-migrate-full <folder>`

**Comment by JamesSingleton** [comment]
So I installed the `ts-migrate` and did `npx ts-migrate-full src`, `npx ts-migrate-full src/`, `npx ts-migrate-full ./src` while inside the library and I get `The system cannot find the path specified`... Does this not work on a Windows machine?

**Comment by shaimalul** [comment]
No matter how I insert the path it always returns 'The system cannot find the path specified'

**Comment by MaximSkvortsov** [comment]
Still have same problem

**Comment by joriewong** [comment]
> Still have same problem

1. `npm install --save-dev ts-migrate`
2. `npx ts-migrate-full ../project-name`

done

**Comment by nosTa1337** [comment]
If you are using windows you can do the following. 

1. Install a linux subsystem following the guide: https://www.windowscentral.com/install-windows-subsystem-linux-windows-10
2. I have installed "Ubuntu 20.04 LTS"
3. When it is installed go to your Visual Studio Code or Command Line into your project path
4. Enter "bash"
5. Install the following:
5.1 sudo apt install unzip
5.2 curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
5.3 sudo apt install nodejs
5.4 sudo npm install --save-dev ts-migrate
5.5 sudo apt install git-all
5.6. login to your git repo
5.6.1 git config --global user.name YOURNAME
5.6.2 git config --global user.email YOUREMAIL
5.7 Create a new Branch
5.8 git checkout -b ts-migrate
5.9 start migration => npx ts-migrate-full .

That's how it worked for me
