### ISSUE TITLE
Problem migrating React 17 app

### ISSUE THREAD

**Issue by studiojms** [airbnb/ts-migrate#84]
Guys, I'm having a problem when trying to migrate a react 17 app from js to typescript using ts-migrate.

I have setup a simple repository where the problem is possible to be reproduced: https://github.com/studiojms/react-ts-migration

Here are steps I did when trying to migrate this repo (with only a few components):

1. First of all, I installed the types dependencies: `yarn add -D @types/react @types/react-dom typescript`
2. Then I installed ts-migrate: `yarn add -D ts-migrate`
3. And I started the process: `npx ts-migrate-full src`
4. When the process started, I just answered yes to the questions, to proceed with the default configurations

And then, I got the following problem:

My react components, which don't have `import React from 'react'` anymore, didn't get converted...

Here is an example of my Button component after migration:

```js
const Button = ({
  onClick,
  children
}: any) => {
  return (
    // @ts-expect-error ts-migrate(2304) FIXME: Cannot find name 'button'.
    <button type="button" onClick={onClick}>
      {children}
    </button>
  );
};

export default Button;

```

It seems like JSX is not recognized. My react components were renamed from js to ts (and not tsx).

Is there anything I could do to make ts-migrate recognize my react components, and migrate them from js to tsx?

I have setup this sample project to test, because I'm trying to migrate a large project (with more than 1000 files), but it turns out it is not recognizing my components... so, this sample project was to verify if it was conflicting with some other stuff in the project

**Comment by studiojms** [comment]
Just fixing the sample project repo url: https://github.com/studiojms/react-ts-migration

**Comment by Rudeg** [comment]
Hi @studiojms, I checked your sample project. 
In this example, react components are not in the `jsx` files, so it fails.
If you will change it from `js` to `jsx`, everything should work.
