### ISSUE TITLE
Use pretty-ms for nicer time formatting

### ISSUE THREAD

**Issue by NickHeiner** [airbnb/ts-migrate#93]
This is minor. In the output, I see:

```
[strip-ts-ignore] Finished in 2214.610ms.
```

The [pretty-ms](http://npmjs.com/package/pretty-ms) package is a simple way to format this in a more human-readable way.

**Comment by Rudeg** [comment]
Thanks! Added - https://github.com/airbnb/ts-migrate/commit/cb17bb09b728c7ed365661fcde87858e3785d7a5 :)

**Comment by NickHeiner** [comment]
Ha! Thanks for the quick turnaround time.
